Invalid argument to use fail

diff --git a/xbt b/xbt
--- a/xbt
+++ b/xbt
@@ -811,6 +811,14 @@ case "$1" in
 		exit 23
 	fi
 	greeting	
+	;;
+
+	
+	invalid_argument)
+    	echo "XBT Error: Invalid argument"
+	exit 1
+	;;
+		
 esac
 exit 5
 }
@@ -840,8 +848,7 @@ if [ "$1" == "--restore" ]; then
 fi
 
 if  [ -n "$1"  ]; then
-    echo "XBT Error: Invalid argument"
-    exit 1
+	fail invalid_argument
 fi
 
 # Greeting user and offering Main Menu:
